### ISSUE TITLE
client session wants read all the time

### ISSUE THREAD

**Issue by icing** [abetterinternet/crustls#109]
In `rustls/src/client/mod.rs` line 445, the client session wants to read before the handshake has started.

It would be nice if it did not do that, since my connection blocks on it. The remote side is waiting for my client hello. 

Sure, i can hack around this, but I'd prefer avoiding to make assumptions about the TLS state engine. Even if this is not likely to change soon.

**Comment by jsha** [comment]
Did you mean to file this against the rustls repo? The file you're referencing is over there.

Also my understanding is that the general model is that you check wants_read and wants_write, and give the appropriate FDs to `select` so you don't have to block if only one possibility is available.

For blocking I/O there's an example in the rustls repo, rustls/src/conn.rs:

```
    fn complete_io<T>(&mut self, io: &mut T) -> Result<(usize, usize), io::Error>
    where
        Self: Sized,
        T: io::Read + io::Write,
    {
        let until_handshaked = self.is_handshaking();
        let mut eof = false;
        let mut wrlen = 0;
        let mut rdlen = 0;

        loop {
            while self.wants_write() {
                wrlen += self.write_tls(io)?;
            }

            if !until_handshaked && wrlen > 0 {
                return Ok((rdlen, wrlen));
            }

            if !eof && self.wants_read() {
                match self.read_tls(io)? {
                    0 => eof = true,
                    n => rdlen += n,
                }
            }
```

Which seems to solve the issue by doing all writes before all reads, which is probably what you'd categorize as "hacking around it." :-)

**Comment by icing** [comment]
I move it to the appropriate crate - I believe `crate-hunting` would be an apt term.
