### ISSUE TITLE
Remove defensive zeroing

### ISSUE THREAD

**Issue by jsha** [abetterinternet/crustls#55]
In [`rustls_server_session_read`](https://github.com/abetterinternet/crustls/blob/cba9836a4ba6bb991c6d965947a753a85d3532d6/src/server.rs#L331-L336) and [`rustls_client_session_read`](https://github.com/abetterinternet/crustls/blob/main/src/client.rs#L315-L320), we receive a buffer from C, turn it into a `&mut [u8]`, zeroize it, and then pass it to `Session::read`.

```
        let read_buf: &mut [u8] = unsafe {
            if buf.is_null() {
                return NullParameter;
            }
            slice::from_raw_parts_mut(buf, count as usize)
        };
        // Since it's *possible* for a Read impl to consume the possibly-uninitialized memory from buf,
        // zero it out just in case. TODO: use Initializer once it's stabilized.
        // https://doc.rust-lang.org/nightly/std/io/trait.Read.html#method.initializer
        for c in read_buf.iter_mut() {
            *c = 0;
        }
```

[RFC 2930 explains this quite well](https://github.com/rust-lang/rfcs/blob/master/text/2930-read-buf.md#summary):

> The current design of the `Read` trait is nonoptimal as it requires that the buffer passed to its various methods be pre-initialized even though the contents will be immediately overwritten. This RFC proposes an interface to allow implementors and consumers of Read types to robustly and soundly work with uninitialized buffers.

However, the current defensive zeroing we have is actually incorrect. [Per `from_raw_parts_mut`](https://doc.rust-lang.org/std/slice/fn.from_raw_parts_mut.html#safety):

> Behavior is undefined if any of the following conditions are violated:
> ...
> `data` must point to `len` consecutive properly initialized values of type `T`.

In other words, if the C code passes us uninitialized memory, we will already have invoked undefined behavior when we called `from_raw_parts_mut`, before we zeroize the memory ourselves.

Also, the zeroizing we do is inefficient. @icing has measured a significant slowdown attributed to it. In practice, we don't need to zeroize memory with each call, we just need to be sure that the memory has well-defined contents (i.e. is not uninitialized). The C caller can do that by allocating a buffer with `calloc` and then reusing it across multiple read calls.

We should remove the zeroization on our side and thoroughly document the requirement that the caller MUST initialize the memory once before passing it to us (and can then reuse the same memory without re-initializing it).

Note that this is fairly risky: the requirement to initialize memory that's going to be overwritten is definitely unintuitive, and relying on documentation to make it happen may not be sufficient. Another approach would be to offer a new opaque struct, `rustls_byte_buffer`, that would be allocated and initialized in Rust. We would change the signature of the `_read` functions to take one of these, so we would be guaranteed to be working with initialized memory. Callers would request one of these with the appropriate size when they create a session, and hang on to it through the session's lifetime, reusing it for efficiency. The struct would be opaque so that users can't create one from uninitialized memory; we would provide access to the underlying bytes via a method.

Also worth noting: There is a semi-related issue that strange Read impls may technically read from their output slice in addition to writing it. We're not worried about that because we know that rustls' Read impls behavior normally and don't read from their input slice.

This seems useful and related but I haven't read it yet: https://www.ralfj.de/blog/2019/07/14/uninit.html (linked from [RFC 2930](https://github.com/rust-lang/rfcs/blob/master/text/2930-read-buf.md#summary)).

**Comment by icing** [comment]
The idea with the `rustls_byte_buffer` would introduce another copying of the data in case of `mod_tls`. In a server like Apache, the part converting plain bytes to encrypted is not the one writing the data on a socket. Instead, the data is passed down to outgoing filters and until it reaches core filters that do the actual write. This part is OS dependant and it has the freedom to buffer that data, based on its best strategy.

That means the lifetime of a `rustls_byte_buffer` is not under control of the code creating it. `mod_tls` would potentially need to create a new `rustls_byte_buffer` for every write. This would be even worse than the zero-ing of the caller supplied memory we have now.

The current `mod_tls` uses `calloc()` for buffers which is fairly efficient. But it, as you stated, relies on the caller to observe the documentation.

However, the blog you linked was very informative. And the explanations it provided all relate to *reading* of uninitialized memory and its non-intuitive side effect. The usage pattern we have here is related to only *writing* of such memory, something that is highly encouraged. but we cannot prevent Rust code to disregard the documentation and do a read before write either.

So, we have to bridge two languages where one says: "you can read uninitialized memory, but it's undefined what happens" and the other: "uninitialized memory does not exist and it's undefined (e.g. behind the curtain) how initialized memory is created".

Meh.

**Comment by jsha** [comment]
Also note that rustls_client_session_write_tls and rustls_server_session_write_tls have the same issue. They don't have the defensive zeroing, but they do build a slice out of memory from the caller, which must be initialized.

> That means the lifetime of a rustls_byte_buffer is not under control of the code creating it. mod_tls would potentially need to create a new rustls_byte_buffer for every write. This would be even worse than the zero-ing of the caller supplied memory we have now.

This is a good point. What I'm proposing with `rustls_byte_buffer` is that one would be created alongside the `rustls_*_session` (maybe even contained within it), and last for the same lifetime, so we wouldn't be allocating on every `read`/`write_tls`, but we would have the problem of copying out of that buffer into somewhere else, as you say.

I'm convinced to go forward with the documentation-dependent approach for now. One other possibility: This problem is created by the [`Read`](https://doc.rust-lang.org/nightly/std/io/trait.Read.html) trait's interface, specifically that it takes a `&mut [u8]` parameter. We could ask rustls for an alternative interface to read out plaintext (and write out TLS bytes) that accepts a `&mut [MaybeUninit<u8>]`, and use that.

**Comment by divergentdave** [comment]
I'd like to chime in with my support for taking a caller-allocated (and initialized) buffer over the `rustls_byte_buffer` solution.

As for the `&mut [MaybeUninit<u8>]` alternative, in the medium term the best way to do this will be with Rust RFC 2930 as mentioned above, which will add `Read::read_buf()`. The implementation work on this is still in progress. If rustls were to add such an API, it would make sense to model it after the proposed `Read::read_buf()`, with a plan to deprecate it once read-buf is landed and stabilized, and put the API there instead.

**Comment by jsha** [comment]
Thanks @divergentdave! I'm looking at the API for `ReadBuf` and trying to figure out how it would fit with caller-provided uninitialized memory. It seems like we would have to instantiate a `ReadBuf` on each call, even if the caller is giving us the same buffer over and over again. The RFC says:

> It is important that we created the ReadBuf outside of the loop. If we instead created it in each loop iteration we would fail to preserve the knowledge of how much of it has been initialized.

In our case, it seems like it would be okay to forget the knowledge of what has been initialized, but that's clearly important to the API design. Is there a downside to rebuilding the ReadBuf on each call?

**Comment by divergentdave** [comment]
I believe the impact is contingent on how the Read impl that you pass the ReadBuf is implemented. If it's a naive Read impl that only implements `Read::read()`, and uses default implementations for everything else, you will pay the price of re-initializing the buffer each time you construct the ReadBuf and call read_buf with it. Similarly, if the `Read:read_buf()` implementation follows the "safe `Read` implementation" outlined in the guide-level explanation, you will pay the same re-initialization costs at the first `buf.initialize_unfilled()` call. However, if it follows the "unsafe `Read` implementation", writing to the buffer through a dereference of a raw `*mut MaybeUninit<u8>` pointer, and then calling `buf.assume_init()`/`buf.add_filled()`, you will entirely avoid extra initialization, and you won't see a penalty for forgetting how much of the buffer is initialized each time.

**Comment by jsha** [comment]
Ah, that makes sense - so the reason `ReadBuf` tracks its initialization state is that a stack of `Read` may include some naive impls and some sophisticated impls, and if you hit a naive impl you'll have to initialize whatever hasn't already been initialized?

**Comment by divergentdave** [comment]
Yeah, that's right. You could think of the read-buf RFC as a "progressive enhancement" mechanism for the Read trait.

Aside from skipping initialization, the two cursors in ReadBuf also allow safe Rust code to call `ReadBuf::filled()` or `ReadBuf::initialized()` and get slices of the buffer, with the pointer dereference and MaybeUninit handling safely encapsulated. That aspect is less important to crustls, since it will just do `buf.filled().len()` and return the length to the C client along with a success result code.
