### ISSUE TITLE
Expected type did not match the received type.

### ISSUE THREAD

**Issue by cute** [abetterinternet/crustls#90]
https://github.com/abetterinternet/crustls/blob/88564644d8fe24a2bf95e1f55ef5e976221be26e/src/client.rs#L465-L469

        let session: &Sess = try_ref_from_ptr!(session);
        match session.session.get_protocol_version() {
            Some(v) => v.get_u16(),
            None => 0
        }

https://github.com/abetterinternet/crustls/blob/88564644d8fe24a2bf95e1f55ef5e976221be26e/src/client.rs#L487-L499

        let session: &Sess = try_ref_from_ptr!(session);
        let protocol_out = try_mut_from_ptr!(protocol_out);
        let protocol_out_len = try_mut_from_ptr!(protocol_out_len);
        match session.session.get_alpn_protocol() {
            Some(p) => {
                *protocol_out = p.as_ptr();
                *protocol_out_len = p.len();
            },
            None => {
                *protocol_out = null();
                *protocol_out_len = 0;
            }
        }

**Comment by jsha** [comment]
This was fixed in #91. Thanks for the report!
